apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
zxcvb
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
zxcvb
  template:
    metadata:
      labels:
        app:
zxcvb
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name:
zxcvb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "49ce5e45-420f-4483-ae24-8c261fdc84c1"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "49ce5e45-420f-4483-ae24-8c261fdc84c1"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
